pipeline:
  name: demo2
  identifier: demo2
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stack1
        identifier: stack1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: stackforlambda
                  identifier: stackforlambda
                  spec:
                    provisionerIdentifier: lambda
                    configuration:
                      stackName: lambda1
                      connectorRef: aws
                      region: us-east-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - Lambda.yaml
                              connectorRef: github
                              repoName: Demo
                              gitFetchType: Branch
                              branch: main
                      roleArn: ""
                  timeout: 10m
        tags: {}
