pipeline:
  name: NewPipeline
  identifier: NewPipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github
        repoName: Demo
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |2-
                                    - step:
                                        type: Run
                                        name: Pytest
                                        identifier: Pytest
                                        spec:
                                          shell: Sh
                                          command: |-
                                            pytest test_main.py --junit-xml=output-test.xml
                                          reports:
                                            type: JUnit
                                            spec:
                                              paths:
                                                - output-test.xml
              - step:
                  type: S3Upload
                  name: S3Upload_1
                  identifier: S3Upload_1
                  spec:
                    connectorRef: aws
                    region: us-east-1
                    bucket: harneestest
                    sourcePath: s3bucket
                    runAsUser: <+input>
                  timeout: <+input>
