AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for creating an S3 bucket
Resources:
   Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: Harnees_test
